"""create heritage knowledge tables

Revision ID: b6e199de17dd
Revises: 
Create Date: 2026-09-11 12:30:54.869405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from backend.common.types import Vec3

# revision identifiers, used by Alembic.
revision: str = 'b6e199de17dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='argon2id'),
    sa.Column('session_token_hash', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False, comment="domain region_code CHECK IN ('hue','da_nang')"),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='toàn văn gốc, để re-chunk'),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True, comment='rút nguồn, không xoá cứng'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('withdrawn_at IS NULL', name='_doc_not_withdrawn'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_region', 'document', ['region'], unique=False)
    op.create_table('predicate',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label_vi', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=True),
    sa.Column('is_symmetric', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('inverse_of', sa.Text(), nullable=True),
    sa.Column('weight', sa.REAL(), server_default='1.0', nullable=False),
    sa.ForeignKeyConstraint(['inverse_of'], ['predicate.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_admin', 'audit_log', ['admin_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_target', 'audit_log', ['target_type', 'target_id'], unique=False)
    op.create_table('passage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('corpus_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text)", persisted=True), nullable=True, comment='generated, do not write'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_end > char_start', name='chk_passage_span'),
    sa.CheckConstraint('char_start >= 0', name='chk_passage_char_start'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'corpus_version', 'char_start', name='uq_passage_span')
    )
    op.create_index('idx_passage_document', 'passage', ['document_id', 'corpus_version'], unique=False)
    op.create_index('idx_passage_tsv', 'passage', ['tsv'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION()), nullable=True, comment='FLOAT8[] - TODO: migrate to VECTOR(1024) after pgvector'),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_passage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('person','place','event','artifact')", name='chk_entity_type'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_passage_id'], ['passage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'type', name='uq_entity_norm')
    )
    op.create_index('idx_entity_name_trgm', 'entity', ['name'], unique=False)
    op.create_index('idx_entity_type', 'entity', ['type'], unique=False)
    op.create_table('entity_alias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('alias_type', sa.String(length=16), server_default='common', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='1.0', nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_passage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alias_type IN ('official','historical','common','typo')", name='chk_alias_type'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='chk_alias_conf'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_passage_id'], ['passage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_alias_entity_norm')
    )
    op.create_index('idx_alias_entity', 'entity_alias', ['entity_id'], unique=False)
    op.create_index('ix_entity_alias_normalized', 'entity_alias', ['normalized_alias'], unique=False)
    op.create_table('place_location',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('ward', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_sentence', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), server_default='pending', nullable=False, comment='pending | verified | rejected | withdrawn'),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'rejected', 'withdrawn')", name='chk_ploc_status'),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='chk_ploc_lat'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='chk_ploc_lng'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='chk_ploc_valid_range'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ploc_entity', 'place_location', ['entity_id'], unique=False)
    op.create_index('ix_ploc_verified', 'place_location', ['verification_status'], unique=False)
    op.create_table('relation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False, comment='FK predicate.code'),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='1.0', nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_passage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='chk_relation_conf'),
    sa.CheckConstraint('subject_id <> object_id', name='chk_relation_loop'),
    sa.ForeignKeyConstraint(['object_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_passage_id'], ['passage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'predicate', 'object_id', name='uq_relation')
    )
    op.create_index('idx_relation_obj', 'relation', ['object_id', 'predicate'], unique=False)
    op.create_index('idx_relation_subj', 'relation', ['subject_id', 'predicate'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_passage_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_passage_id'], ['passage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_entity', 'site', ['entity_id'], unique=False)
    op.create_table('chat_session',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ip_hash', sa.Text(), nullable=False, comment='hash để anonymize'),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_ip', 'chat_session', ['ip_hash', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('scene',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('transform_7dof', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='JSONB {translate:[x,y,z],rotate:[x,y,z,w],scale:n}'),
    sa.Column('bbox_min', Vec3(), nullable=True),
    sa.Column('bbox_max', Vec3(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(transform_7dof ? 'translate') AND (transform_7dof ? 'rotate') AND (transform_7dof ? 'scale')", name='chk_scene_7dof'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scene_site', 'scene', ['site_id', 'order_index'], unique=False)
    op.create_table('tour',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=8), server_default='vi', nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('location_label', sa.Text(), nullable=True),
    sa.Column('splash_image_url', sa.Text(), nullable=True),
    sa.Column('ambient_audio_url', sa.Text(), nullable=True),
    sa.Column('default_sky', sa.String(length=32), server_default='midday', nullable=False),
    sa.Column('default_camera_clip_url', sa.Text(), nullable=True, comment='flythrough mở đầu'),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False, comment='ETag + chống ghi đè'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='NULL = draft, API ẩn'),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['admin_account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'locale', name='uq_tour_slug_locale')
    )
    op.create_index('idx_tour_pub', 'tour', ['slug', 'locale'], unique=False, postgresql_where=sa.text('published_at IS NOT NULL'))
    op.create_index('idx_tour_site', 'tour', ['site_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('abstained', sa.Boolean(), server_default='false', nullable=False, comment='từ chối trả lời ngoài phạm vi'),
    sa.Column('retrieval_strategy', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('corpus_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role = 'user' OR abstained OR jsonb_array_length(citations) > 0", name='chk_msg_citations'),
    sa.CheckConstraint("role IN ('user','assistant')", name='chk_msg_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_session', 'chat_message', ['session_id', 'created_at'], unique=False)
    op.create_table('model_asset',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('lod_level', sa.Integer(), nullable=False, comment='0 = cao nhất'),
    sa.Column('file_url', sa.Text(), nullable=False, comment='URL CDN, KHÔNG lưu blob'),
    sa.Column('content_hash', sa.Text(), nullable=True, comment='cache-busting tên file'),
    sa.Column('format', sa.String(length=16), server_default='glb', nullable=False),
    sa.Column('compression', sa.String(length=32), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('triangle_count', sa.BigInteger(), nullable=True),
    sa.Column('gpu_bytes', sa.BigInteger(), nullable=True),
    sa.Column('is_proxy', sa.Boolean(), server_default='false', nullable=False, comment='bản nhẹ raycast/preview'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('glb','gltf','splat','sog','ply')", name='chk_asset_format'),
    sa.CheckConstraint('file_size_bytes > 0', name='chk_asset_size'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'lod_level', name='uq_asset_scene_lod')
    )
    op.create_index('idx_asset_scene', 'model_asset', ['scene_id', 'lod_level'], unique=False)
    op.create_table('raw_asset',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('capture_method', sa.String(length=32), nullable=False),
    sa.Column('storage_location', sa.Text(), nullable=False, comment='path local/SSD ngoài, không public'),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("capture_method IN ('photogrammetry','gaussian_splat_source','drone_video','lidar')", name='chk_capture_method'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_scene', 'raw_asset', ['scene_id'], unique=False)
    op.create_table('story',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='HTML'),
    sa.Column('camera_clip_url', sa.Text(), nullable=True),
    sa.Column('camera_name', sa.Text(), nullable=True, comment='chọn camera trong file nhiều camera'),
    sa.Column('clip_start_s', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('clip_end_s', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('start_camera_position', Vec3(), nullable=True),
    sa.Column('start_camera_target', Vec3(), nullable=True),
    sa.Column('zoom_camera_position', Vec3(), nullable=True),
    sa.Column('zoom_camera_target', Vec3(), nullable=True),
    sa.Column('camera_fov', sa.REAL(), nullable=True, comment='CHECK 10..120'),
    sa.Column('pan_enable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('instant_move', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sky', sa.String(length=32), nullable=True, comment='NULL = kế thừa tour.default_sky'),
    sa.Column('free_explore', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('explore_area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(zoom_camera_position IS NULL) = (zoom_camera_target IS NULL)', name='chk_story_zoom_pair'),
    sa.CheckConstraint('NOT free_explore OR explore_area IS NOT NULL', name='chk_story_explore'),
    sa.CheckConstraint('camera_clip_url IS NOT NULL OR start_camera_position IS NOT NULL', name='chk_story_has_camera'),
    sa.CheckConstraint('clip_start_s IS NULL OR clip_end_s IS NULL OR clip_end_s > clip_start_s', name='chk_story_clip_range'),
    sa.CheckConstraint('start_camera_position IS NULL OR start_camera_target IS NULL OR start_camera_position <> start_camera_target', name='chk_story_pos_ne_target'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_id', 'order_index', name='uq_story_order')
    )
    op.create_index('idx_story_scene', 'story', ['scene_id'], unique=False)
    op.create_index('idx_story_tour', 'story', ['tour_id', 'order_index'], unique=False)
    op.create_table('chat_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False, comment='(-1, 1)'),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IN (-1, 1)', name='chk_feedback_rating'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('highlight',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='NULLABLE: không phải highlight nào cũng là entity trong KG'),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('orb_position', Vec3(), nullable=False, comment='vị trí quả cầu'),
    sa.Column('camera_position', Vec3(), nullable=False, comment='pose khi bấm vào'),
    sa.Column('camera_target', Vec3(), nullable=False),
    sa.Column('popup_title', sa.Text(), nullable=False),
    sa.Column('popup_text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=True),
    sa.Column('media_caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_type IS NULL OR media_type IN ('image','video','audio','model')", name='chk_hl_media_type'),
    sa.CheckConstraint('(media_url IS NULL) = (media_type IS NULL)', name='chk_hl_media_pair'),
    sa.CheckConstraint('camera_position <> camera_target', name='chk_hl_cam_ne_tgt'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scene.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hl_entity', 'highlight', ['entity_id'], unique=False)
    op.create_index('idx_hl_story', 'highlight', ['story_id', 'order_index'], unique=False)
    op.create_table('narration',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=False),
    sa.Column('captions_vtt_url', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='FE dùng để tính drift'),
    sa.Column('voice_credit', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms > 0', name='chk_narration_duration'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id')
    )
    op.create_table('transcript',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_ms > start_ms', name='chk_transcript_span'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'seq', name='uq_transcript_seq')
    )
    op.create_index('idx_transcript_story', 'transcript', ['story_id', 'seq'], unique=False)
    op.create_table('citation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=True),
    sa.Column('transcript_id', sa.UUID(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(passage_id IS NOT NULL)::int + (transcript_id IS NOT NULL)::int = 1', name='chk_citation_one_source'),
    sa.ForeignKeyConstraint(['passage_id'], ['passage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_citation_passage', 'citation', ['passage_id'], unique=False)
    op.create_index('idx_citation_transcript', 'citation', ['transcript_id'], unique=False)
    op.execute("""
CREATE VIEW v_tour_stop AS
SELECT
  t.id                AS tour_id,
  t.slug,
  t.locale,
  t.title             AS tour_title,
  t.tagline,
  t.location_label,
  t.splash_image_url,
  t.ambient_audio_url,
  t.default_camera_clip_url,
  t.revision,
  t.published_at,

  s.id                AS story_id,
  s.order_index,
  s.title             AS scene_title,
  s.description       AS scene_description,
  s.camera_clip_url,
  s.camera_name,
  s.clip_start_s,
  s.clip_end_s,
  s.start_camera_position,
  s.start_camera_target,
  s.zoom_camera_position,
  s.zoom_camera_target,
  s.camera_fov,
  s.pan_enable,
  s.instant_move,
  COALESCE(s.sky, t.default_sky) AS sky,
  s.free_explore,
  s.explore_area,

  sc.bbox_min,
  sc.bbox_max,
  sc.transform_7dof,
  (SELECT ma.file_url FROM model_asset ma
    WHERE ma.scene_id = s.scene_id AND NOT ma.is_proxy
    ORDER BY ma.lod_level LIMIT 1) AS model_url,

  n.audio_url         AS narration_url,
  n.captions_vtt_url,
  n.duration_ms       AS narration_duration_ms,

  COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
      'id',              h.id,
      'entity_id',       h.entity_id,
      'popup_title',     h.popup_title,
      'popup_text',      h.popup_text,
      'media_url',       h.media_url,
      'media_type',      h.media_type,
      'media_caption',   h.media_caption,
      'orb_position',    h.orb_position,
      'camera_position', h.camera_position,
      'camera_target',   h.camera_target
    ) ORDER BY h.order_index)
    FROM highlight h WHERE h.story_id = s.id
  ), '[]'::jsonb) AS highlights

FROM tour t
JOIN story s        ON s.tour_id  = t.id
LEFT JOIN scene sc  ON sc.id      = s.scene_id
LEFT JOIN narration n ON n.story_id = s.id;
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The view depends on tour/story/scene/narration, so it must be removed first.
    op.execute("DROP VIEW IF EXISTS v_tour_stop")
    op.drop_index('idx_citation_transcript', table_name='citation')
    op.drop_index('idx_citation_passage', table_name='citation')
    op.drop_table('citation')
    op.drop_index('idx_transcript_story', table_name='transcript')
    op.drop_table('transcript')
    op.drop_table('narration')
    op.drop_index('idx_hl_story', table_name='highlight')
    op.drop_index('idx_hl_entity', table_name='highlight')
    op.drop_table('highlight')
    op.drop_table('chat_feedback')
    op.drop_index('idx_story_tour', table_name='story')
    op.drop_index('idx_story_scene', table_name='story')
    op.drop_table('story')
    op.drop_index('idx_raw_scene', table_name='raw_asset')
    op.drop_table('raw_asset')
    op.drop_index('idx_asset_scene', table_name='model_asset')
    op.drop_table('model_asset')
    op.drop_index('idx_msg_session', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('idx_tour_site', table_name='tour')
    op.drop_index('idx_tour_pub', table_name='tour', postgresql_where=sa.text('published_at IS NOT NULL'))
    op.drop_table('tour')
    op.drop_index('idx_scene_site', table_name='scene')
    op.drop_table('scene')
    op.drop_index('idx_session_ip', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_index('idx_site_entity', table_name='site')
    op.drop_table('site')
    op.drop_index('idx_relation_subj', table_name='relation')
    op.drop_index('idx_relation_obj', table_name='relation')
    op.drop_table('relation')
    op.drop_index('ix_ploc_verified', table_name='place_location')
    op.drop_index('idx_ploc_entity', table_name='place_location')
    op.drop_table('place_location')
    op.drop_index('ix_entity_alias_normalized', table_name='entity_alias')
    op.drop_index('idx_alias_entity', table_name='entity_alias')
    op.drop_table('entity_alias')
    op.drop_index('idx_entity_type', table_name='entity')
    op.drop_index('idx_entity_name_trgm', table_name='entity')
    op.drop_table('entity')
    op.drop_index('idx_passage_tsv', table_name='passage')
    op.drop_index('idx_passage_document', table_name='passage')
    op.drop_table('passage')
    op.drop_index('idx_audit_target', table_name='audit_log')
    op.drop_index('idx_audit_admin', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('predicate')
    op.drop_index('idx_document_region', table_name='document')
    op.drop_table('document')
    op.drop_table('admin_account')
    # ### end Alembic commands ###
